<?php

use App\Accomodation;

use Illuminate\Database\Seeder;


class AccomodationSeeder extends Seeder
{
   /**
    * Run the database seeds.
    *
    * @return void
    */
   public function run()
   {
      $accomodations = [

         // ROMA - DAJE!
         [
            'title' => "Intero alloggio (casa)",
            'description' => 'Situato a due passi del centro storico di Roma e dalla Stazione Trastevere questo delizioso loft gode di una location privilegiata che permette di esplorare la città a piedi.',
            'number_rooms' => 4,
            'number_bathrooms' => 2,
            'number_beds' => 2,
            'square_mts' => 130,
            'price_per_night' => 30,
            'visibility' => true,
            'country' => 'Italy',
            'city' => 'Roma',
            'province' => 'Roma',
            'type_street' => 'Via',
            'street_name' => 'Muzio Clementi',
            'building_number' => 81,
            'zip' => '00193',
            'lat' => 41.90980,
            'lon' => 12.47235,
            'placeholder' => "",
            'user_id' => 1,
            'check_in' => 12,
            'check_out' => 10,
            'count_services' => 0,
         ],
         [
            'title' => 'Artists House - CENTRUM - Campo de fiori',
            'description' => "Appartamento situato in un palazzo medioevale del 1200. E' stato completamenete ristrutturato, con rifiniture di lusso: wifi, computer, Tv Grande schermo HD, impianto stereo centralizzato, cassaforte a muro.",
            'number_rooms' => 5,
            'number_bathrooms' => 3,
            'number_beds' => 3,
            'square_mts' => 120,
            'price_per_night' => 40,
            'visibility' => true,
            'country' => 'Italy',
            'city' => 'Roma',
            'province' => 'Roma',
            'type_street' => 'Via',
            'street_name' => ' Giorgio Perlasca',
            'building_number' => 13,
            'zip' => '00155',
            'lat' => 41.90235,
            'lon' => 12.56785,
            'placeholder' => "",
            'user_id' => 2,
            'check_in' => 12,
            'check_out' => 10,
            'count_services' => 0,
         ],
         [
            'title' => 'Domus Chiavari House',
            'description' =>   "Situata nell'incantevole quartiere di Campo de Fiori, in uno dei più caratteristici vicoli di Roma, a pochi metri dal Pantheon, Piazza Navona e Piazza Venezia, la Domus Campo de' Fiori offre un grazioso appartamento, finemente decorato e posto al piano terra di un delizioso cortile condominiale. La struttura dispone di angolo cottura attrezzato, macchina da caffè, soggiorno con divano e area dining e bagno con doccia set di cortesia.",
            'number_rooms' => 5,
            'number_bathrooms' => 3,
            'number_beds' => 3,
            'square_mts' => 120,
            'price_per_night' => 40,
            'visibility' => true,
            'country' => 'Italy',
            'city' => 'Roma',
            'province' => 'Roma',
            'type_street' => 'Via',
            'street_name' => 'Salaria',
            'building_number' => 1223,
            'zip' => '00138',
            'lat' => 41.992283,
            'lon' => 12.51055,
            'placeholder' => "",
            'user_id' => 3,
            'check_in' => 13,
            'check_out' => 10,
            'count_services' => 0,
         ],
         [
            'title' => 'Boheme Cottage with swimming pool',
            'description' =>   "Boheme Cottage si trova nella parte sud di Roma e ha un bel giardino tutto intorno. Nelle vicinanze si trova l'area archeologica del Parco dell'Appia Antica e il Santuario di Santa Maria del Divino Amore. La piscina è aperta da fine maggio a fine settembre",
            'number_rooms' => 3,
            'number_bathrooms' => 1,
            'number_beds' => 2,
            'square_mts' => 120,
            'price_per_night' => 68,
            'visibility' => true,
            'country' => 'Italy',
            'city' => 'Roma',
            'province' => 'Roma',
            'type_street' => 'Via',
            'street_name' => 'Antonio Zanoni',
            'building_number' => 51,
            'zip' => '00134',
            'lat' => 41.47018,
            'lon' => 12.514640,
            'placeholder' => "",
            'user_id' => 4,
            'check_in' => 18,
            'check_out' => 14,
            'count_services' => 0,
         ],
         [
            'title' => 'Mini House.',
            'description' =>   "Il mini appartamento, completamente ristrutturato nel 2018, si trova in un piccolo appartamento costruito nel 1930. La sua posizione all'ultimo piano (4 ° piano senza ascensore) garantisce una splendida vista sulla città. È possibile rilassarsi dopo una giornata intensa di visite turistiche. Puoi fare una siesta, bere un bicchiere di vino o goderti il cielo serale sull'amaca colorata sull'enorme terrazza piena di piante di questo arioso appartamento, desiderare di sentirti come un locale dopo lunghe giornate nelle zone turistiche. Molti bei ristoranti frequentati principalmente da gente del posto",
            'number_rooms' => 2,
            'number_bathrooms' => 1,
            'number_beds' => 1,
            'square_mts' => 45,
            'price_per_night' => 50,
            'visibility' => true,
            'country' => 'Italy',
            'city' => 'Roma',
            'province' => 'Roma',
            'type_street' => 'Via',
            'street_name' => 'Luigi Tosti',
            'building_number' => 28,
            'zip' => '00179',
            'lat' => 41.87233,
            'lon' => 12.51840,
            'placeholder' => "",
            'user_id' => 5,
            'check_in' => 15,
            'check_out' => 11,
            'count_services' => 0,
         ],
         [
            'title' => 'Pettinarihome Campo de Fiori',
            'description' =>   "Il nostro appartamento e' una suite di 25 mq. a pochi passi da Campo de Fiori, Ponte Sisto, Piazza Trilussa, Piazza Navona, situato in un palazzetto del 1600, al 3 ed ultimo piano senza ascensore, molto luminoso e tranquillo, la struttura puo' ospitare n 2 persone, la suite e' stata recentemente ristrutturata ed e' fornita di ogni comfort, compreso nel prezzo anche una deliziosa (website hidden) prenotazione possiamo offrire ai nostri clienti un servizio di taxi, dall'Aeroporto al centro di Roma, e viceversa, dal centro di Roma all'Aeroporto di partenza, questo servizio e' esclusivamente per i nostri ospiti. Distanze indicative calcolate in linea d'aria da BED AND BREAKFAST PETTINARIHOME CAMPO DE FIORI, per alcuni punti di grandi dimensioni, sono calcolate dal centro. Clicca sul luogo per vedere il percorso stradale.",
            'number_rooms' => 1,
            'number_bathrooms' => 1,
            'number_beds' => 1,
            'square_mts' => 25,
            'price_per_night' => 45,
            'visibility' => true,
            'country' => 'Italy',
            'city' => 'Roma',
            'province' => 'Roma',
            'type_street' => 'Via',
            'street_name' => 'dei pettinari',
            'building_number' => 53,
            'zip' => '00186',
            'lat' => 41.892912,
            'lon' => 12.471453,
            'placeholder' => "",
            'user_id' => 1,
            'check_in' => 12,
            'check_out' => 10,
            'count_services' => 0,
         ],
         [
            'title' => 'Colosseo Corner',
            'description' =>   "COLOSSEO alla tua porta di casa, non può andare meglio di così. Decorato con alcune insegne nostalgiche che completano l'aspetto vintage di questo appartamento.
            Davvero perfetto per una coppia e gli amici che cercano una fuga veloce",
            'number_rooms' => 4,
            'number_bathrooms' => 1,
            'number_beds' => 4,
            'square_mts' => 80,
            'price_per_night' => 115,
            'visibility' => true,
            'country' => 'Italy',
            'city' => 'Roma',
            'province' => 'Roma',
            'type_street' => 'Via',
            'street_name' => 'di S.Giovanni Laterano',
            'building_number' => 55,
            'zip' => '00179',
            'lat' => 41.888904,
            'lon' => 12.438991,
            'placeholder' => "",
            'user_id' => 2,
            'check_in' => 14,
            'check_out' => 10,
            'count_services' => 0,
         ],
         [
            'title' => 'La Casa di Monte Giordano 1',
            'description' => "L'appartamento si trova nel cuore di Roma, a pochi passi dalle maggiori attrazioni della città. Situato in una delle zone più antiche e storiche. È dotato di tutto il necessario per trascorrere un soggiorno confortevole. Si trova al piano terra di un antico edificio del XVII secolo in una piccola e pittoresca strada, equidistante da Piazza Navona e Castel Sant' Angelo.",
            'number_rooms' => 1,
            'number_bathrooms' => 1,
            'number_beds' => 1,
            'square_mts' => 30,
            'price_per_night' => 55,
            'visibility' => true,
            'country' => 'Italy',
            'city' => 'Roma',
            'province' => 'Roma',
            'type_street' => 'Via',
            'street_name' => 'di Monte Giordano',
            'building_number' => 1,
            'zip' => '00186',
            'lat' => 41.899433,
            'lon' => 12.469845,
            'placeholder' => "",
            'user_id' => 3,
            'check_in' => 16,
            'check_out' => 10,
            'count_services' => 0,
         ],
         [
            'title' => 'Camera zona San Pietro',
            'description' => "Camera doppia situata al centro di Roma uso singola con i seguenti servizi en-suite: bagno privato,tv-sat,frigo,aria condizionata,wi-fi, cassaforte, bollitore",
            'number_rooms' => 1,
            'number_bathrooms' => 1,
            'number_beds' => 1,
            'square_mts' => 20,
            'price_per_night' => 45,
            'visibility' => true,
            'country' => 'Italy',
            'city' => 'Roma',
            'province' => 'Roma',
            'type_street' => 'Viale',
            'street_name' => 'Angelico',
            'building_number' => 30,
            'zip' => '00195',
            'lat' => 41.914833,
            'lon' => 12.458694,
            'placeholder' => "",
            'user_id' => 4,
            'check_in' => 15,
            'check_out' => 11,
            'count_services' => 0,
         ],
         [
            'title' => 'Historic center Campo dei Fiori',
            'description' => "Ottima posizione nel cuore del centro storico di Roma, situato tra il ghetto ebraico e Campo dei fiori. Si trova in un palazzo storico del 1700 con volte a stella, piano terra, completamente ristrutturato e arredato, zona notte con soppalco di 2 metri, divano soggiorno, riscaldamento autonomo, lavatrice, aria condizionata, wi-fi.",
            'number_rooms' => 2,
            'number_bathrooms' => 1,
            'number_beds' => 1,
            'square_mts' => 45,
            'price_per_night' => 65,
            'visibility' => true,
            'country' => 'Italy',
            'city' => 'Roma',
            'province' => 'Roma',
            'type_street' => 'Via',
            'street_name' => 'Arenula',
            'building_number' => 26,
            'zip' => '00186',
            'lat' => 41.893231,
            'lon' => 12.475478,
            'placeholder' => "",
            'user_id' => 5,
            'check_in' => 12,
            'check_out' => 11,
            'count_services' => 0,
         ],
         [
            'title' => 'Casa "Vicolo della Torre" - TRASTEVERE',
            'description' => "Trastevere, raffinato Loft nel centro di Roma,
            completamente ristrutturato nel 2019.
            Finemente arredato, dotato di ogni comodità, caratteristico e funzionale, con entrata indipendente e check-in automatico, ti sentirai libero di godere della vera atmosfera di Roma. La posizione è eccezionale tutti i monumenti più famosi sono raggiungibile a piedi, ma è anche vicino ai mezzi pubblici, market, negozi per lo shopping e pub, qui potrai deliziarti con i menù tipici nelle molteplici osterie romane!",
            'number_rooms' => 2,
            'number_bathrooms' => 1,
            'number_beds' => 1,
            'square_mts' => 50,
            'price_per_night' => 85,
            'visibility' => true,
            'country' => 'Italy',
            'city' => 'Roma',
            'province' => 'Roma',
            'type_street' => 'Vicolo',
            'street_name' => 'della Torre',
            'building_number' => 3,
            'zip' => '00153',
            'lat' => 41.889451,
            'lon' => 12.472550,
            'placeholder' => "",
            'user_id' => 1,
            'check_in' => 13,
            'check_out' => 10,
            'count_services' => 0,
         ],
         [
            'title' => 'Colosseo Superior Apartment',
            'description' => "Siamo nel cuore di Roma, a pochi passi dal Colosseo e dalla Basilica di San Giovanni in Laterano. Passeggiando si possono comodamente raggiungere molti dei principali luoghi di interesse storico, culturale e di intrattenimento.
            Vicinissimo alla metro e a diverse fermate di autobus, situato in una via silenziosa, al riparo dal traffico e dal caos cittadino, vi accogliamo in un edificio indipendente completamente ristrutturato, composto da sei piccoli appartamenti.",
            'number_rooms' => 3,
            'number_bathrooms' => 1,
            'number_beds' => 2,
            'square_mts' => 80,
            'price_per_night' => 105,
            'visibility' => true,
            'country' => 'Italy',
            'city' => 'Roma',
            'province' => 'Roma',
            'type_street' => 'Via',
            'street_name' => 'Domenico Fontana',
            'building_number' => 24,
            'zip' => '00185',
            'lat' => 41.887917,
            'lon' => 12.507082,
            'placeholder' => "",
            'user_id' => 2,
            'check_in' => 14,
            'check_out' => 10,
            'count_services' => 0,
         ],
         [
            'title' => 'Casa Villa Statilia 5',
            'description' => "Villa Statilia 5 è una stupendo monolocale con bagno, situato al centro di Roma in un luogo comodissimo per visitare la città, ma allo stesso tempo molto tranquillo e silenzioso. Il grande patio esterno attrezzato la rendono un' oasi di pace dove assaporare al meglio l'atmosfera della Città Eterna.
            Comodissimo l'uso di una cucina comune, un distributore automatico e la possibilità di affittare in loco delle biciclette.",
            'number_rooms' => 2,
            'number_bathrooms' => 1,
            'number_beds' => 1,
            'square_mts' => 45,
            'price_per_night' => 75,
            'visibility' => true,
            'country' => 'Italy',
            'city' => 'Roma',
            'province' => 'Roma',
            'type_street' => 'Via',
            'street_name' => 'Statilia',
            'building_number' => 5,
            'zip' => '00185',
            'lat' => 41.889635,
            'lon' => 12.509096,
            'placeholder' => "",
            'user_id' => 3,
            'check_in' => 16,
            'check_out' => 12,
            'count_services' => 0,
         ],
         [
            'title' => 'Green loft Trastevere',
            'description' => "Loft nel cuore di Roma zona Trastevere, ottima posizione, intero appartamento a disposizione, self check-in, dotato di tutti i comfort e servizi, cucina, Tv Wi-fi inclusi.",
            'number_rooms' => 2,
            'number_bathrooms' => 1,
            'number_beds' => 1,
            'square_mts' => 40,
            'price_per_night' => 95,
            'visibility' => true,
            'country' => 'Italy',
            'city' => 'Roma',
            'province' => 'Roma',
            'type_street' => 'Via',
            'street_name' => 'dei Panieri',
            'building_number' => 48,
            'zip' => '00153',
            'lat' => 41.890254,
            'lon' => 12.466335,
            'placeholder' => "",
            'user_id' => 4,
            'check_in' => 13,
            'check_out' => 11,
            'count_services' => 0,
         ],
         [
            'title' => 'B&B S.Paolo - stanza blu 2',
            'description' => "Stanza blu numero 2: ampia camera di circa 15 metri quadrati nel cuore di Roma al confine tra il il rione Testaccio e la Garbatella. vicino alla Piramide (fermata metro linea B) ed a 10 minuti dal Colosseo-Foro Romano. Colazione inclusa nel prezzo, letto matrimoniale, bagno privato con GRANDE doccia, asciugamani, aria condizionata fresca e calda, WI-FI, TV, mini frigo e GRANDE terrazzo. 2 ospiti massimo. ",
            'number_rooms' => 2,
            'number_bathrooms' => 1,
            'number_beds' => 1,
            'square_mts' => 45,
            'price_per_night' => 75,
            'visibility' => true,
            'country' => 'Italy',
            'city' => 'Roma',
            'province' => 'Roma',
            'type_street' => 'Via',
            'street_name' => 'dei Conciatori',
            'building_number' => 1,
            'zip' => '00154',
            'lat' => 41.874323,
            'lon' => 12.480140,
            'placeholder' => "",
            'user_id' => 5,
            'check_in' => 14,
            'check_out' => 11,
            'count_services' => 0,
         ],
         [
            'title' => 'Trevi Luxuri - Attico',
            'description' => "Appartamento delizioso situato in una tranquilla e storica via a pochi passi dalla magica Fontana di Trevi e dalla famosa Piazza di Spagna. Questo piccolo attico si affaccia sui tetti di Roma e dispone di una terrazzetta dalla quale si può godere di un panorama suggestivo e romantico. Appena ristrutturato l'appartamento dispone di tutti i comfort: wi fi, aria condizionata, riscaldamento, smart tv 50 pollici, cucina attrezzata tavola e ferro da stiro.
            Lo spazio
            L' appartamento si trova al 5 piano di uno storico e signorile palazzo nel centro di Roma ed è provvisto di ascensore. Grazie al fatto di trovarsi all ultimo piano e di disporre di ampie finestre, l 'appartamento è estremamente luminoso.",
            'number_rooms' => 2,
            'number_bathrooms' => 1,
            'number_beds' => 1,
            'square_mts' => 60,
            'price_per_night' => 100,
            'visibility' => true,
            'country' => 'Italy',
            'city' => 'Roma',
            'province' => 'Roma',
            'type_street' => 'Via',
            'street_name' => 'del Lavoratore',
            'building_number' => 30,
            'zip' => '00187',
            'lat' => 41.901302,
            'lon' => 12.484814,
            'placeholder' => "",
            'user_id' => 1,
            'check_in' => 13,
            'check_out' => 11,
            'count_services' => 0,
         ],
         [
            'title' => 'Graziosa mansarda con vista sul Pantheon',
            'description' => "Pittoresca mansarda con travi a vista e magnifico affaccio sulla piazza del Pantheon, nel cuore di Roma, composta da camera con letto matrimoniale, smart tv e aria condizionata; seconda stanza con cucina e divano letto per 1 adulto o 2 bambini (larghezza 140 cm.); bagno con doccia.
            Materasso e cuscini confortevoli.
            L'appartamento è dotato di WI-FI, lavatrice, stendibiancheria, ferro e asse da stiro, frigo con piccolo freezer, forno a micronde e tutto il necessario per cucinare.",
            'number_rooms' => 2,
            'number_bathrooms' => 1,
            'number_beds' => 1,
            'square_mts' => 55,
            'price_per_night' => 85,
            'visibility' => true,
            'country' => 'Italy',
            'city' => 'Roma',
            'province' => 'Roma',
            'type_street' => 'Piazza',
            'street_name' => 'Capranica',
            'building_number' => 72,
            'zip' => '00186',
            'lat' => 41.899981,
            'lon' => 12.477889,
            'placeholder' => "",
            'user_id' => 2,
            'check_in' => 12,
            'check_out' => 10,
            'count_services' => 0,
         ],
         [
            'title' => 'Happy Giulia',
            'description' => "Situato nello storico quartiere popolare di San Lorenzo, questo caratteristico bilocale si trova a 10 minuti a piedi dalla stazione Termini, Basilica di San Giovanni, Basilica di Santa Maria Maggiore, Piazza Vittorio, Terme di Diocleziano, Palazzo delle Esposizioni, Rione Monti e altro ancora. L'appartamento offre una discreta tranquillità, pur trovandosi in un quartiere giovane, vicino alla città universitaria, ricco di vita notturna, locali alla moda, cucina tipica e varietà di locali da pranzo.",
            'number_rooms' => 3,
            'number_bathrooms' => 1,
            'number_beds' => 3,
            'square_mts' => 55,
            'price_per_night' => 75,
            'visibility' => true,
            'country' => 'Italy',
            'city' => 'Roma',
            'province' => 'Roma',
            'type_street' => 'Via',
            'street_name' => 'Livorno',
            'building_number' => 5,
            'zip' => '00162',
            'lat' => 41.914600,
            'lon' => 12.521859,
            'placeholder' => "",
            'user_id' => 3,
            'check_in' => 15,
            'check_out' => 12,
            'count_services' => 0,
         ],
         [
            'title' => 'Bilocale Roma - ghetto ebraico',
            'description' => "Ghetto Ebraico, piano terra, bilocale 40 mq, salone e camera letto, soffitto a cassettoni e cotto, completamente ristrutturato e arredato, piastra induzione, lavatrice, piccolo bagno con doccia, aria condizionata, wi-fi.",
            'number_rooms' => 2,
            'number_bathrooms' => 1,
            'number_beds' => 2,
            'square_mts' => 45,
            'price_per_night' => 75,
            'visibility' => true,
            'country' => 'Italy',
            'city' => 'Roma',
            'province' => 'Roma',
            'type_street' => 'Piazza',
            'street_name' => 'Benedetto Cairoli',
            'building_number' => 5,
            'zip' => '00186',
            'lat' => 41.893889,
            'lon' => 12.475148,
            'placeholder' => "",
            'user_id' => 4,
            'check_in' => 16,
            'check_out' => 14,
            'count_services' => 0,
         ],
         [
            'title' => 'Colosseo Design Apartment',
            'description' => "Questo appartamento elegante e moderno si trova a soli 5 minuti a piedi dal Colosseo e dal Foro Romano e dispone dei servizi alberghieri più elevati.",
            'number_rooms' => 3,
            'number_bathrooms' => 1,
            'number_beds' => 3,
            'square_mts' => 105,
            'price_per_night' => 185,
            'visibility' => true,
            'country' => 'Italy',
            'city' => 'Roma',
            'province' => 'Roma',
            'type_street' => 'Via',
            'street_name' => 'degli Annibaldi',
            'building_number' => 8,
            'zip' => '00162',
            'lat' => 41.892469,
            'lon' => 12.491732,
            'placeholder' => "",
            'user_id' => 5,
            'check_in' => 12,
            'check_out' => 10,
            'count_services' => 0,
         ],


         // MILANO - Ape sui navigli TAC!!
         [
            'title' => 'Intero alloggio',
            'description' => "Elegante appartamento di 90mq in Piazza Tommaseo, a pochi passi dalla stazione metropolitana Conciliazione (linea MM1 - rossa), in un quartiere aristocratico nel pieno centro di Milano.",
            'number_rooms' => 1,
            'number_bathrooms' => 1,
            'number_beds' => 1,
            'square_mts' => 90,
            'price_per_night' => 150,
            'visibility' => true,
            'country' => 'Italy',
            'city' => 'Milano',
            'province' => 'Milano',
            'type_street' => 'Piazza',
            'street_name' => 'Nicolò Tommaseo',
            'building_number' => 2,
            'zip' => '20123',
            'lat' => 45.469776,
            'lon' =>  9.166800,
            'placeholder' => "",
            'user_id' => 1,
            'check_in' => 16,
            'check_out' => 11,
            'count_services' => 0,
         ],
         [
            'title' => 'Intero alloggio',
            'description' => "Accogliente monolocale sui Navigli, perfetto per chi vuole visitare Milano. Appena ristrutturato, l'appartamento è in posizione centrale e a pochi passi dal Duomo. La zona è ricca di ristoranti e locali caratteristici per vivere al meglio la città. Ideale per gli studenti degli istituti NABA (distante letteralmente 3 minuti a piedi), IULM e Bocconi.",
            'number_rooms' => 2,
            'number_bathrooms' => 1,
            'number_beds' => 4,
            'square_mts' => 90,
            'price_per_night' => 70,
            'visibility' => true,
            'country' => 'Italy',
            'city' => 'Milano',
            'province' => 'Milano',
            'type_street' => 'Via',
            'street_name' => "dell'Orso",
            'building_number' => 7,
            'zip' => '20121',
            'lat' => 45.4724691,
            'lon' =>  9.1861503,
            'placeholder' => "",
            'user_id' => 2,
            'check_in' => 14,
            'check_out' => 11,
            'count_services' => 0,
         ],
         [
            'title' => "PrimoPiano - XXII Marzo",
            'description' => "Loft in contesto ex industriale con posto auto. Living room con zona pranzo, piccola cucina, bagno, soppalco con zona notte.",
            'number_rooms' => 6,
            'number_bathrooms' => 5,
            'number_beds' => 9,
            'square_mts' => 100,
            'price_per_night' => 135,
            'visibility' => true,
            'country' => 'Italy',
            'city' => 'Milano',
            'province' => 'Milano',
            'type_street' => 'Via',
            'street_name' => 'Arcangelo Corelli',
            'building_number' => 56,
            'zip' => '20134',
            'lat' => 45.47319,
            'lon' => 9.25395,
            'placeholder' => "",
            'user_id' => 3,
            'check_in' => 12,
            'check_out' => 10,
            'count_services' => 0,
         ],
         [
            'title' => "Loft Garden",
            'description' => "Soggiornare a pochi passi dal Duomo di Milano, cattedrale simbolo della città e uno dei monumenti più belli e suggestivi al mondo in appartamenti di ricercato design, completi di tutte le comodità possibili per rendere il vostro soggiorno speciale e vivere un sogno a occhi aperti.",
            'number_rooms' => 7,
            'number_bathrooms' => 4,
            'number_beds' => 4,
            'square_mts' => 90,
            'price_per_night' => 115,
            'visibility' => true,
            'country' => 'Italy',
            'city' => 'Milano',
            'province' => 'Milano',
            'type_street' => 'Via',
            'street_name' => 'Caldera',
            'building_number' => 3,
            'zip' => '20153',
            'lat' => 45.480654,
            'lon' =>  9.1040962,
            'placeholder' => "",
            'user_id' => 4,
            'check_in' => 12,
            'check_out' => 10,
            'count_services' => 0,
         ],
         [
            'title' => "Villetta a schiera",
            'description' => "Una deliziosa villeta a schiera in stile moderno, perfetta per coppie e famiglie.",
            'number_rooms' => 4,
            'number_bathrooms' => 2,
            'number_beds' => 3,
            'square_mts' => 120,
            'price_per_night' => 105,
            'visibility' => true,
            'country' => 'Italy',
            'city' => 'Milano',
            'province' => 'Milano',
            'type_street' => 'Via',
            'street_name' => 'Alessandro Litta',
            'building_number' => 93,
            'zip' => '20161',
            'lat' => 45.52176,
            'lon' =>  9.15377,
            'placeholder' => "",
            'user_id' => 5,
            'check_in' => 14,
            'check_out' => 11,
            'count_services' => 0,
         ],
         [
            'title' => "Casa di design in zona centrale",
            'description' => "Grazioso piccolo loft al secondo piano di una caratteristica casa di ringhiera milanese, silenziosa e accogliente.
            Ottima posizione a 5 min a piedi dalla Stazione centrale. Si trova a due passi da Piazza Gae Aulenti (Corso Como), dal Duomo di Milano, Isola, Corso Buenos Aires,Porta Venezia.",
            'number_rooms' => 3,
            'number_bathrooms' => 1,
            'number_beds' => 3,
            'square_mts' => 55,
            'price_per_night' => 85,
            'visibility' => true,
            'country' => 'Italy',
            'city' => 'Milano',
            'province' => 'Milano',
            'type_street' => 'Via',
            'street_name' => 'Alfredo Campanini',
            'building_number' => 6,
            'zip' => '20124',
            'lat' => 45.48607,
            'lon' =>  9.19822,
            'placeholder' => "",
            'user_id' => 1,
            'check_in' => 13,
            'check_out' => 10,
            'count_services' => 0,
         ],
         [
            'title' => "Cozy Apartment Blue",
            'description' => "Grazioso appartamento Situato in zona Stazione Centrale/ Corso Buenos Aires, a pochi passi dalla stazione e pochi minuti dal centro, comoda per i servizi e mezzi nelle vicinanze.
            Contesto signorile con portineria
            Appartamento al piano terra, recentemente ristrutturato, completamente arredato e dotato di tutti i confort (lavatrice, biancheria casa, TV, macchina del caffè, Asciugacapelli, Wifii…)
            Perfetta sia per Visitare la città di Milano sia per viaggi di lavoro.",
            'number_rooms' => 2,
            'number_bathrooms' => 1,
            'number_beds' => 2,
            'square_mts' => 60,
            'price_per_night' => 90,
            'visibility' => true,
            'country' => 'Italy',
            'city' => 'Milano',
            'province' => 'Milano',
            'type_street' => 'Via',
            'street_name' => 'Tonale',
            'building_number' => 24,
            'zip' => '20125',
            'lat' => 45.48964,
            'lon' =>  9.20179,
            'placeholder' => "",
            'user_id' => 2,
            'check_in' => 13,
            'check_out' => 11,
            'count_services' => 0,
         ],
         [
            'title' => "PrimoPiano - Gluck Flat",
            'description' => "Ampio monolocale attrezzato con TV, internet WiFi, cucina a parete, divano letto e bagno con doccia.",
            'number_rooms' => 1,
            'number_bathrooms' => 1,
            'number_beds' => 1,
            'square_mts' => 30,
            'price_per_night' => 65,
            'visibility' => true,
            'country' => 'Italy',
            'city' => 'Milano',
            'province' => 'Milano',
            'type_street' => 'Via',
            'street_name' => 'Cristoforo Gluck',
            'building_number' => 37,
            'zip' => '20125',
            'lat' => 45.493424,
            'lon' =>  9.208948,
            'placeholder' => "",
            'user_id' => 3,
            'check_in' => 12,
            'check_out' => 10,
            'count_services' => 0,
         ],
         [
            'title' => "Ampio bilocale - Stazione Centrale",
            'description' => "SELF CHECK-IN APERTURA PORTE CON CELLULARE dalle 15:00, check-out entro le 10:00. Luminoso ampio bilocale a 5 minuti a piedi da Stazione Centrale. Stanza da letto con 1 letto matrimoniale, soggiorno con un divano letto 2 piazze. Aria condizionata, Wi-fi 200mb, SmartTV.
            [CIR: 015146-CNI-00438]",
            'number_rooms' => 2,
            'number_bathrooms' => 1,
            'number_beds' => 2,
            'square_mts' => 90,
            'price_per_night' => 100,
            'visibility' => true,
            'country' => 'Italy',
            'city' => 'Milano',
            'province' => 'Milano',
            'type_street' => 'Via',
            'street_name' => 'Gianfranco Zuretti',
            'building_number' => 23,
            'zip' => '20125',
            'lat' => 45.49311,
            'lon' =>  9.20727,
            'placeholder' => "",
            'user_id' => 4,
            'check_in' => 15,
            'check_out' => 10,
            'count_services' => 0,
         ],
         [
            'title' => "La casa sui tetti",
            'description' => "Godetevi questo silenzioso appartamento situato in uno dei quartieri più caratteristici e pulp di Milano. Arredato in modo funzionale e ideale per qualsiasi tipologia di viaggiatore, offre un ottimo spazio anche per necessità di homeworking.
            Moderno, elegante e tranquillo, si trova in una posizione strategica sia che siate a Milano per affari che per puro svago.
            Situato a pochi passi dalla Stazione Centrale e a 3 min da Corso Buenos Aires e Piazza Gae Aulenti.",
            'number_rooms' => 1,
            'number_bathrooms' => 1,
            'number_beds' => 1,
            'square_mts' => 30,
            'price_per_night' => 65,
            'visibility' => true,
            'country' => 'Italy',
            'city' => 'Milano',
            'province' => 'Milano',
            'type_street' => 'Via',
            'street_name' => 'Napo Torriani',
            'building_number' => 9,
            'zip' => '20124',
            'lat' => 45.4841446,
            'lon' =>  9.20331,
            'placeholder' => "",
            'user_id' => 5,
            'check_in' => 12,
            'check_out' => 10,
            'count_services' => 0,
         ],


         // VENEZIA - OSTREGHETA!
         [
            'title' => "La casa degli Angeli",
            'description' => "Lo spazio è costituito da un grande monolocale con cucina e bagno..per dormire c è un divano letto molto comodo..lo spazio è munito di condizionatore...pala e ventilatore..due televisioni e lavatrice.",
            'number_rooms' => 6,
            'number_bathrooms' => 3,
            'number_beds' => 5,
            'square_mts' => 70,
            'price_per_night' => 55,
            'visibility' => true,
            'country' => 'Italy',
            'city' => 'Venezia',
            'province' => 'Venezia',
            'type_street' => 'Piazza',
            'street_name' => '27 Ottobre',
            'building_number' => 91,
            'zip' => '30172',
            'lat' => 45.4952676,
            'lon' =>  12.242072,
            'placeholder' => "",
            'user_id' => 1,
            'check_in' => 12,
            'check_out' => 10,
            'count_services' => 0,
         ],
         [
            'title' => "Intero alloggio: unità in affitto",
            'description' => "Il soffitto dell'appartamento è il tipico soffitto veneziano con i travi in legno a vista. Il parquet di legno bianco fa risaltare gli spazi e la luminosità dell'appartamento. L'appartamento è stato arredato e restaurato di recente. La zona in cui è ubicato l'appartamento è molto caratteristica e centrale. ",
            'number_rooms' => 6,
            'number_bathrooms' => 3,
            'number_beds' => 5,
            'square_mts' => 70,
            'price_per_night' => 55,
            'visibility' => true,
            'country' => 'Italy',
            'city' => 'Venezia',
            'province' => 'Venezia',
            'type_street' => 'Piazza',
            'street_name' => 'Campo Santa Maria del Giglio',
            'building_number' => 2494,
            'zip' => '30124',
            'lat' => 45.43509,
            'lon' =>  12.332401,
            'placeholder' => "",
            'user_id' => 2,
            'check_in' => 12,
            'check_out' => 10,
            'count_services' => 0,
         ],
         [
            'title' => "Venezia... esageratamente Venezia!",
            'description' => "Il soffitto dell'appartamento è il tipico soffitto veneziano con i travi in legno a vista. Il parquet di legno bianco fa risaltare gli spazi e la luminosità dell'appartamento. L'appartamento è stato arredato e restaurato di recente. La zona in cui è ubicato l'appartamento è molto caratteristica e centrale. A solo qualche minuto a piedi si raggiunge il famosissimo Ponte di Rialto e attraversandolo si arriva nell'area del Mercato del Pesce e delle Osterie.",
            'number_rooms' => 2,
            'number_bathrooms' => 1,
            'number_beds' => 2,
            'square_mts' => 70,
            'price_per_night' => 65,
            'visibility' => true,
            'country' => 'Italy',
            'city' => 'Venezia',
            'province' => 'Venezia',
            'type_street' => 'Calle',
            'street_name' => 'de la Bissa',
            'building_number' => 1,
            'zip' => '30124',
            'lat' => 45.438325,
            'lon' =>  12.337059,
            'placeholder' => "",
            'user_id' => 3,
            'check_in' => 15,
            'check_out' => 10,
            'count_services' => 0,
         ],
         [
            'title' => "Spacious with stunning views!",
            'description' => "Appartamento molto spazioso, luminoso e restaurato nel quartiere più locale di Venezia. Da ogni finestra è possibile gettare uno sguardo sui tetti, un ampio canale e un giardino. In pochi minuti a piedi troverai i punti salienti della città ei ristoranti migliori e più economici di Venezia. L'appartamento è situato tra la stazione ferroviaria/terminal delle auto e Piazza San Marco.
            È molto facile raggiungerlo, non importa come si arriva a Venezia (la fermata del vaporetto è a soli 4 minuti di distanza).",
            'number_rooms' => 4,
            'number_bathrooms' => 1,
            'number_beds' => 5,
            'square_mts' => 110,
            'price_per_night' => 155,
            'visibility' => true,
            'country' => 'Italy',
            'city' => 'Venezia',
            'province' => 'Venezia',
            'type_street' => 'Calle',
            'street_name' => 'dei Riformati',
            'building_number' => 3213,
            'zip' => '30121',
            'lat' => 45.447199,
            'lon' =>  12.326657,
            'placeholder' => "",
            'user_id' => 4,
            'check_in' => 12,
            'check_out' => 10,
            'count_services' => 0,
         ],
         [
            'title' => "Floating house in the authentic Venice",
            'description' => "Appartamento romantico con una vista unica. Nuovo ed elegante questo è il loft ideale per una coppia o una famiglia che vuole vivere il sogno romantico di Venezia con una vista unica e meravigliosa del Canal e della Gondola di Venezia. L'appartamento è riservato, silenzioso, spazioso e confortevole e si trova in un autentico e tipico quartiere veneziano ricco di ristoranti, bar, negozi frequentati dai veneziani vicino alla stazione, ai vaporetti e ai principali punti di interesse Rialto e Piazza San Marco",
            'number_rooms' => 4,
            'number_bathrooms' => 1,
            'number_beds' => 3,
            'square_mts' => 85,
            'price_per_night' => 95,
            'visibility' => true,
            'country' => 'Italy',
            'city' => 'Venezia',
            'province' => 'Venezia',
            'type_street' => 'Calle',
            'street_name' => 'Groppi',
            'building_number' => 2543,
            'zip' => '30121',
            'lat' => 45.444931,
            'lon' =>  12.332019,
            'placeholder' => "",
            'user_id' => 5,
            'check_in' => 14,
            'check_out' => 12,
            'count_services' => 0,
         ],


         // FIRENZE - Maremma boia!
         [
            'title' => "Ampia stanza",
            'description' => "Ampia stanza di 25 mq con ingresso indipendente e bagno privato al primo piano di un antico edificio del centro storico, a 200 metri da Piazza della Signoria, Uffizi e Piazza Santa Croce.
            A pochi passi si trovano molti ristoranti tipici e negozi. La via è molto tranquilla e l'affaccio della stanza su una corte interna la rende particolarmente silenziosa.",
            'number_rooms' => 1,
            'number_bathrooms' => 1,
            'number_beds' => 2,
            'square_mts' => 25,
            'price_per_night' => 68,
            'visibility' => true,
            'country' => 'Italy',
            'city' => 'Firenze',
            'province' => 'Firenze',
            'type_street' => 'Via',
            'street_name' => 'degli Orti Oricellari',
            'building_number' => 30,
            'zip' => '50123',
            'lat' => 43.784229,
            'lon' =>  11.2480423,
            'placeholder' => "",
            'user_id' => 1,
            'check_in' => 12,
            'check_out' => 10,
            'count_services' => 0,
         ],
         [
            'title' => "La casa degli Angeli",
            'description' => "Lo spazio è costituito da un grande monolocale con cucina e bagno..per dormire c è un divano letto molto comodo..lo spazio è munito di condizionatore...pala e ventilatore..due televisioni e lavatrice.",
            'number_rooms' => 3,
            'number_bathrooms' => 2,
            'number_beds' => 3,
            'square_mts' => 40,
            'price_per_night' => 87,
            'visibility' => true,
            'country' => 'Italy',
            'city' => 'Firenze',
            'province' => 'Firenze',
            'type_street' => 'Via',
            'street_name' => 'Giulio Caccini',
            'building_number' => 24,
            'zip' => '50141',
            'lat' => 43.80690,
            'lon' =>  11.24392,
            'placeholder' => "",
            'user_id' => 2,
            'check_in' => 12,
            'check_out' => 10,
            'count_services' => 0,
         ],
         [
            'title' => "Vigna Vecchia Modern Studio",
            'description' => "Moderno monolocale di 15mq in grado di ospitare fino a due persone. Collocato al secondo piano (senza ascensore) di uno stabile antico in buone condizioni, l'alloggio si trova in zona Santa Croce, posizione ideale per visitare al meglio la città di Firenze e tutti i principali punti di interesse. Siamo a 5 minuti di distanza a piedi da Piazza della Signoria e 10 da Ponte Vecchio.",
            'number_rooms' => 3,
            'number_bathrooms' => 2,
            'number_beds' => 3,
            'square_mts' => 40,
            'price_per_night' => 87,
            'visibility' => true,
            'country' => 'Italy',
            'city' => 'Firenze',
            'province' => 'Firenze',
            'type_street' => 'Via',
            'street_name' => 'Maragliano',
            'building_number' => 69,
            'zip' => '50144',
            'lat' => 43.78844,
            'lon' =>  11.23312,
            'placeholder' => "",
            'user_id' => 3,
            'check_in' => 12,
            'check_out' => 10,
            'count_services' => 0,
         ],
         [
            'title' => "Maggio Tower View",
            'description' => "Loft prestigioso situato a Firenze in zona Oltrarno, con vista mozzafiato a 360 gradi su tutti i monumenti fiorentini. Ideale per affitti di breve periodo. Ambiente unico, composto di zona salotto, zona notte, bagno completo, angolo cucina. Può ospitare 2 persone.",
            'number_rooms' => 2,
            'number_bathrooms' => 1,
            'number_beds' => 1,
            'square_mts' => 65,
            'price_per_night' => 93,
            'visibility' => true,
            'country' => 'Italy',
            'city' => 'Firenze',
            'province' => 'Firenze',
            'type_street' => 'Via',
            'street_name' => 'Maragliano',
            'building_number' => 69,
            'zip' => '50144',
            'lat' => 43.78844,
            'lon' =>  11.23312,
            'placeholder' => "",
            'user_id' => 4,
            'check_in' => 12,
            'check_out' => 10,
            'count_services' => 0,
         ], 
         [
            'title' => "Vigna Vecchia Modern Studio",
            'description' => "Moderno monolocale di 15mq in grado di ospitare fino a due persone. Collocato al secondo piano (senza ascensore) di uno stabile antico in buone condizioni, l'alloggio si trova in zona Santa Croce, posizione ideale per visitare al meglio la città di Firenze e tutti i principali punti di interesse. Siamo a 5 minuti di distanza a piedi da Piazza della Signoria e 10 da Ponte Vecchio.",
            'number_rooms' => 3,
            'number_bathrooms' => 2,
            'number_beds' => 3,
            'square_mts' => 40,
            'price_per_night' => 87,
            'visibility' => true,
            'country' => 'Italy',
            'city' => 'Firenze',
            'province' => 'Firenze',
            'type_street' => 'Via',
            'street_name' => 'Maragliano',
            'building_number' => 69,
            'zip' => '50144',
            'lat' => 43.78844,
            'lon' =>  11.23312,
            'placeholder' => "",
            'user_id' => 5,
            'check_in' => 12,
            'check_out' => 10,
            'count_services' => 0,
         ],
      ];

      foreach ($accomodations as $accomodation) {
         $new_accomodation = new Accomodation();

         $new_accomodation->fill($accomodation);

         $new_accomodation->save();
      }
   }
}
